class CfgFunctions {
	class APS {
		class Default {
			file = "src\scripts\APS";
			class active { headerType = WL_HEADER_LEVEL; };
			class apsHandler { headerType = WL_HEADER_LEVEL; };
			class ciws { headerType = WL_HEADER_LEVEL; };
			class cram { headerType = WL_HEADER_LEVEL; };
			class defineVehicles { headerType = WL_HEADER_LEVEL; };
			class deviceJammer { headerType = WL_HEADER_LEVEL; };
			class friendlyWarning { headerType = WL_HEADER_LEVEL; };
			class getDirection { headerType = WL_HEADER_LEVEL; };
			class getMaxAmmo { headerType = WL_HEADER_LEVEL; };
			class lagProtection { headerType = WL_HEADER_LEVEL; };
			class lagProtectionServer { headerType = WL_HEADER_LEVEL; };
			class limitMines { headerType = WL_HEADER_LEVEL; };
			class projectileStateUpdate { headerType = WL_HEADER_LEVEL; };
			class rearmAPS { headerType = WL_HEADER_LEVEL; };
			class registerVehicle { headerType = WL_HEADER_LEVEL; };
			class relDir2 { headerType = WL_HEADER_LEVEL; };
			class report { headerType = WL_HEADER_LEVEL; };
			class sead { headerType = WL_HEADER_LEVEL; };
			class setupProjectiles { headerType = WL_HEADER_LEVEL; };
			class serverHandleAPS { headerType = WL_HEADER_LEVEL; };
			class toggle { headerType = WL_HEADER_LEVEL; };
		};
	};
	class DIS {
		class Default {
			file = "src\scripts\DIS";
			class advancedSam { headerType = WL_HEADER_LEVEL; };
			class bunkerBuster { headerType = WL_HEADER_LEVEL; };
			class calculateInRange { headerType = WL_HEADER_LEVEL; };
			class combatAirPatrol { headerType = WL_HEADER_LEVEL; };
			class controlMunition { headerType = WL_HEADER_LEVEL; };
			class droneDeployer { headerType = WL_HEADER_LEVEL; };
			class extendedSam { headerType = WL_HEADER_LEVEL; };
			class frag { headerType = WL_HEADER_LEVEL; };
			class getLaserList { headerType = WL_HEADER_LEVEL; };
			class getMissileType { headerType = WL_HEADER_LEVEL; };
			class getNotchResult { headerType = WL_HEADER_LEVEL; };
			class getSamTarget { headerType = WL_HEADER_LEVEL; };
			class getSeadTarget { headerType = WL_HEADER_LEVEL; };
			class getSquadList { headerType = WL_HEADER_LEVEL; };
			class getTargetList { headerType = WL_HEADER_LEVEL; };
			class gpsMunition { headerType = WL_HEADER_LEVEL; };
			class handleGPSKeypress { headerType = WL_HEADER_LEVEL; };
			class handleKeypress { headerType = WL_HEADER_LEVEL; };
			class laserMunition { headerType = WL_HEADER_LEVEL; };
			class loalAuto { headerType = WL_HEADER_LEVEL; };
			class maneuver { headerType = WL_HEADER_LEVEL; };
			class mineLayer { headerType = WL_HEADER_LEVEL; };
			class missileCamera { headerType = WL_HEADER_LEVEL; };
			class remoteMunition { headerType = WL_HEADER_LEVEL; };
			class seekTerminal { headerType = WL_HEADER_LEVEL; };
			class setupExtendedSam { headerType = WL_HEADER_LEVEL; };
			class setupTargetingMenu { headerType = WL_HEADER_LEVEL; };
			class startMissileCamera { headerType = WL_HEADER_LEVEL; };
			class terminalGuidance { headerType = WL_HEADER_LEVEL; };
			class tvMunition { headerType = WL_HEADER_LEVEL; };
		};
	};
	class GFE {
		class Default {
			file = "src\scripts\GFE";
			class credits { headerType = WL_HEADER_LEVEL; };
			class earplugs { headerType = WL_HEADER_LEVEL; };
		};
	};
	class KST {
		class Default {
			file = "src\scripts\KST";
			class actions { headerType = WL_HEADER_LEVEL; };
			class explode { headerType = WL_HEADER_LEVEL; };
			class jetpack { headerType = WL_HEADER_LEVEL; };
			class rocket { headerType = WL_HEADER_LEVEL; };
			class setParent { headerType = WL_HEADER_LEVEL; };
			class tracers { headerType = WL_HEADER_LEVEL; };
		};
	};
	class MENU {
		class Default {
			file = "src\scripts\MENU";
			class copyChat { headerType = WL_HEADER_LEVEL; };
			class debugMenu { headerType = WL_HEADER_LEVEL; };
			class execCode { headerType = WL_HEADER_LEVEL; };
			class modMenu { headerType = WL_HEADER_LEVEL; };
			class playerDataRefresh { headerType = WL_HEADER_LEVEL; };
			class playerReported { headerType = WL_HEADER_LEVEL; };
			class printSystemTime { headerType = WL_HEADER_LEVEL; };
			class reportMenu { headerType = WL_HEADER_LEVEL; };
			class reportPlayer { headerType = WL_HEADER_LEVEL; };
			class resetDefault { headerType = WL_HEADER_LEVEL; };
			class sendModData { headerType = WL_HEADER_LEVEL; };
			class sendReportData { headerType = WL_HEADER_LEVEL; };
			class setReturnValue { headerType = WL_HEADER_LEVEL; };
			class settingsMenu { headerType = WL_HEADER_LEVEL; };
			class settingsMenuInit { headerType = WL_HEADER_LEVEL; };
			class updateViewDistance { headerType = WL_HEADER_LEVEL; };
		};
	};
	class PERF {
		class Default {
			file = "src\scripts\PERF";
			class perfMenuInit { headerType = WL_HEADER_LEVEL; };
		};
	};
	class POLL {
		class Default {
			file = "src\scripts\POLL";
			class pollAction { headerType = WL_HEADER_LEVEL; };
			class pollMenu { headerType = WL_HEADER_LEVEL; };
			class selectOption { headerType = WL_HEADER_LEVEL; };
			class updatePollMenu { headerType = WL_HEADER_LEVEL; };
		};
	};
	class RWD {
		class Default {
			file = "src\scripts\RWD";
			class addBadge { headerType = WL_HEADER_LEVEL; };
			class applyBadge { headerType = WL_HEADER_LEVEL; };
			class badgeMenu { headerType = WL_HEADER_LEVEL; };
			class getBadgeConfigs { headerType = WL_HEADER_LEVEL; };
			class handleBadge { headerType = WL_HEADER_LEVEL; };
			class handleReward { headerType = WL_HEADER_LEVEL; };
			class newBadge { headerType = WL_HEADER_LEVEL; };
		};
	};
	class SPEC {
		class Default {
			file = "src\scripts\SPEC";
			class spectator { headerType = WL_HEADER_LEVEL; };
			class spectator3P { headerType = WL_HEADER_LEVEL; };
			class spectatorFree { headerType = WL_HEADER_LEVEL; };
			class spectatorMap { headerType = WL_HEADER_LEVEL; };
			class spectatorMenu { headerType = WL_HEADER_LEVEL; };
			class spectatorRewardProxy { headerType = WL_HEADER_LEVEL; };
			class spectatorSelectTarget { headerType = WL_HEADER_LEVEL; };
			class spectatorDraw3d { headerType = WL_HEADER_LEVEL; };
			class spectatorGetIcon { headerType = WL_HEADER_LEVEL; };
			class spectatorTarget { headerType = WL_HEADER_LEVEL; };
		};
	};
	class SQD {
		class Default {
			file = "src\scripts\SQD";
			class actionSpawn { headerType = WL_HEADER_LEVEL; };
			class actionVehicle { headerType = WL_HEADER_LEVEL; };
			class client { headerType = WL_HEADER_LEVEL; };
			class contextBadge { headerType = WL_HEADER_LEVEL; };
			class contextInvite { headerType = WL_HEADER_LEVEL; };
			class contextPlayer { headerType = WL_HEADER_LEVEL; };
			class contextSquad { headerType = WL_HEADER_LEVEL; };
			class contextVehicle { headerType = WL_HEADER_LEVEL; };
			class executeSpawn { headerType = WL_HEADER_LEVEL; };
			class initClient { headerType = WL_HEADER_LEVEL; };
			class initDeathInfo { headerType = WL_HEADER_LEVEL; };
			class initServer { headerType = WL_HEADER_LEVEL; };
			class initSquadMenu { headerType = WL_HEADER_LEVEL; };
			class query { headerType = WL_HEADER_LEVEL; };
			class renderSquads { headerType = WL_HEADER_LEVEL; };
			class renderSpawns { headerType = WL_HEADER_LEVEL; };
			class renderStatus { headerType = WL_HEADER_LEVEL; };
			class renderText { headerType = WL_HEADER_LEVEL; };
			class renderVehicles { headerType = WL_HEADER_LEVEL; };
			class server { headerType = WL_HEADER_LEVEL; };
			class setSpawnCam { headerType = WL_HEADER_LEVEL; };
		};
	};
	class WL2 {
		class Client {
			file = "src\core\client";
			class addMissileToMag { headerType = WL_HEADER_LEVEL; };
			class afk { headerType = WL_HEADER_LEVEL; };
			class airburst { headerType = WL_HEADER_LEVEL; };
			class ammoConfigChange { headerType = WL_HEADER_LEVEL; };
			class ammoConfigDetection { headerType = WL_HEADER_LEVEL; };
			class announcer { headerType = WL_HEADER_LEVEL; };
			class announcerInit { headerType = WL_HEADER_LEVEL; };
			class betty { headerType = WL_HEADER_LEVEL; };
			class broadcastAction { headerType = WL_HEADER_LEVEL; };
			class clientEH { headerType = WL_HEADER_LEVEL; };
			class combatAirClient { headerType = WL_HEADER_LEVEL; };
			class combatAirWarning { headerType = WL_HEADER_LEVEL; };
			class commMenu { headerType = WL_HEADER_LEVEL; };
			class commMenuListen { headerType = WL_HEADER_LEVEL; };
			class createDestroyerClient { headerType = WL_HEADER_LEVEL; };
			class earthquake { headerType = WL_HEADER_LEVEL; };
			class ewar { headerType = WL_HEADER_LEVEL; };
			class ewar2 { headerType = WL_HEADER_LEVEL; };
			class ewarMessage { headerType = WL_HEADER_LEVEL; };
			class exitToLobby { headerType = WL_HEADER_LEVEL; };
			class factionBasedClientInit { headerType = WL_HEADER_LEVEL; };
			class handleAIDamage { headerType = WL_HEADER_LEVEL; };
			class handleAIDown { headerType = WL_HEADER_LEVEL; };
			class handleBuyMenuKeypress { headerType = WL_HEADER_LEVEL; };
			class handleChatMessages { headerType = WL_HEADER_LEVEL; };
			class handleKeypress { headerType = WL_HEADER_LEVEL; };
			class handlePlayerDamage { headerType = WL_HEADER_LEVEL; };
			class handlePlayerDown { headerType = WL_HEADER_LEVEL; };
			class incendiary { headerType = WL_HEADER_LEVEL; };
			class initClient { headerType = WL_HEADER_LEVEL; };
			class interceptAction { headerType = WL_HEADER_LEVEL; };
			class isDrone { headerType = WL_HEADER_LEVEL; };
			class lagMessageDisplay { headerType = WL_HEADER_LEVEL; };
			class locationScanner { headerType = WL_HEADER_LEVEL; };
			class mutePlayer { headerType = WL_HEADER_LEVEL; };
			class onPause { headerType = WL_HEADER_LEVEL; };
			class onPlayerRespawn { headerType = WL_HEADER_LEVEL; };
			class particleEffect { headerType = WL_HEADER_LEVEL; };
			class pingFix { headerType = WL_HEADER_LEVEL; };
			class pingFixInit { headerType = WL_HEADER_LEVEL; };
			class pingSounds { headerType = WL_HEADER_LEVEL; };
			class playerEventHandlers { headerType = WL_HEADER_LEVEL; };
			class playSoundArrival { headerType = WL_HEADER_LEVEL; };
			class prompt { headerType = WL_HEADER_LEVEL; };
			class publishSelfLog { headerType = WL_HEADER_LEVEL; };
			class rebalanced { headerType = WL_HEADER_LEVEL; };
			class repackMagazines { headerType = WL_HEADER_LEVEL; };
			class reportTargets { headerType = WL_HEADER_LEVEL; };
			class resetVehicle { headerType = WL_HEADER_LEVEL; };
			class restrictedArea { headerType = WL_HEADER_LEVEL; };
			class revive { headerType = WL_HEADER_LEVEL; };
			class rewardCapture { headerType = WL_HEADER_LEVEL; };
			class setupCarrier { headerType = WL_HEADER_LEVEL; };
			class showHint { headerType = WL_HEADER_LEVEL; };
			class showRating { headerType = WL_HEADER_LEVEL; };
			class sidePicker { headerType = WL_HEADER_LEVEL; };
			class sideToFaction { headerType = WL_HEADER_LEVEL; };
			class spawnAtBase { headerType = WL_HEADER_LEVEL; };
			class smartMine { headerType = WL_HEADER_LEVEL; };
			class spectrumInterface { headerType = WL_HEADER_LEVEL; };
			class surrenderWarning { headerType = WL_HEADER_LEVEL; };
			class surveillance { headerType = WL_HEADER_LEVEL; };
			class teammatesAvailability { headerType = WL_HEADER_LEVEL; };
			class timedPrompt { headerType = WL_HEADER_LEVEL; };
			class triggerPurchase { headerType = WL_HEADER_LEVEL; };
			class updateLevelDisplay { headerType = WL_HEADER_LEVEL; };
			class welcome { headerType = WL_HEADER_LEVEL; };
			class writeResult { headerType = WL_HEADER_LEVEL; };
		};
		class ClientAction {
			file = "src\core\client\action";
			class actionLockCamera { headerType = WL_HEADER_LEVEL; };
			class afkAction { headerType = WL_HEADER_LEVEL; };
			class airRadarAction { headerType = WL_HEADER_LEVEL; };
			class airRearmAction { headerType = WL_HEADER_LEVEL; };
			class airWreckHandler { headerType = WL_HEADER_LEVEL; };
			class arsenalSetup { headerType = WL_HEADER_LEVEL; };
			class attachVehicle { headerType = WL_HEADER_LEVEL; };
			class autoSam { headerType = WL_HEADER_LEVEL; };
			class buyMenuAction { headerType = WL_HEADER_LEVEL; };
			class catapultAction { headerType = WL_HEADER_LEVEL; };
			class catapultActionEligibility { headerType = WL_HEADER_LEVEL; };
			class claimAction { headerType = WL_HEADER_LEVEL; };
			class claimEligibility { headerType = WL_HEADER_LEVEL; };
			class conscription { headerType = WL_HEADER_LEVEL; };
			class conscriptVehicle { headerType = WL_HEADER_LEVEL; };
			class controlDroneActions { headerType = WL_HEADER_LEVEL; };
			class controlGunnerAction { headerType = WL_HEADER_LEVEL; };
			class controlGunnerEligibility { headerType = WL_HEADER_LEVEL; };
			class demolishAction { headerType = WL_HEADER_LEVEL; };
			class demolishEligibility { headerType = WL_HEADER_LEVEL; };
			class demolishStep { headerType = WL_HEADER_LEVEL; };
			class deployableAddAction { headerType = WL_HEADER_LEVEL; };
			class deployableEligibility { headerType = WL_HEADER_LEVEL; };
			class ecmAction { headerType = WL_HEADER_LEVEL; };
			class fieldRepairEligibility { headerType = WL_HEADER_LEVEL; };
			class getVehicleLockStatus { headerType = WL_HEADER_LEVEL; };
			class grapple { headerType = WL_HEADER_LEVEL; };
			class hmdSendData { headerType = WL_HEADER_LEVEL; };
			class hmdSettings { headerType = WL_HEADER_LEVEL; };
			class hmdSettingsAction { headerType = WL_HEADER_LEVEL; };
			class installAction { headerType = WL_HEADER_LEVEL; };
			class laserWeapon { headerType = WL_HEADER_LEVEL; };
			class lockActionEligibility { headerType = WL_HEADER_LEVEL; };
			class lockActionUpdate { headerType = WL_HEADER_LEVEL; };
			class mineClearAction { headerType = WL_HEADER_LEVEL; };
			class nearestCombatAir { headerType = WL_HEADER_LEVEL; };
			class parachuteAction { headerType = WL_HEADER_LEVEL; };
			class parachuteSetup { headerType = WL_HEADER_LEVEL; };
			class paradropperAction { headerType = WL_HEADER_LEVEL; };
			class placeRespawnBag { headerType = WL_HEADER_LEVEL; };
			class radarOperateAction { headerType = WL_HEADER_LEVEL; };
			class radarOperateUpdate { headerType = WL_HEADER_LEVEL; };
			class radarRotateAction { headerType = WL_HEADER_LEVEL; };
			class radarRotateUpdate { headerType = WL_HEADER_LEVEL; };
			class rappelAction { headerType = WL_HEADER_LEVEL; };
			class rappelActionEligibility { headerType = WL_HEADER_LEVEL; };
			class rearmAction { headerType = WL_HEADER_LEVEL; };
			class rearmActionEligibility { headerType = WL_HEADER_LEVEL; };
			class rearmAPSEligibility { headerType = WL_HEADER_LEVEL; };
			class rebase { headerType = WL_HEADER_LEVEL; };
			class rebaseActionEligibility { headerType = WL_HEADER_LEVEL; };
			class reconOpticsAction { headerType = WL_HEADER_LEVEL; };
			class reconReward { headerType = WL_HEADER_LEVEL; };
			class refuelAction { headerType = WL_HEADER_LEVEL; };
			class refuelActionEligibility { headerType = WL_HEADER_LEVEL; };
			class removeAction { headerType = WL_HEADER_LEVEL; };
			class removeAsset { headerType = WL_HEADER_LEVEL; };
			class removeStronghold { headerType = WL_HEADER_LEVEL; };
			class repairAction { headerType = WL_HEADER_LEVEL; };
			class repairActionEligibility { headerType = WL_HEADER_LEVEL; };
			class repairActionUpdate { headerType = WL_HEADER_LEVEL; };
			class restockAction { headerType = WL_HEADER_LEVEL; };
			class reviveAction { headerType = WL_HEADER_LEVEL; };
			class runwayBuster { headerType = WL_HEADER_LEVEL; };
			class scanner { headerType = WL_HEADER_LEVEL; };
			class scannerAction { headerType = WL_HEADER_LEVEL; };
			class secureWreck { headerType = WL_HEADER_LEVEL; };
			class secureWreckAction { headerType = WL_HEADER_LEVEL; };
			class setupForwardBaseAction { headerType = WL_HEADER_LEVEL; };
			class setupForwardBaseEligibility { headerType = WL_HEADER_LEVEL; };
			class setupForwardBaseMp { headerType = WL_HEADER_LEVEL; };
			class setupIntegralWeaponAction { headerType = WL_HEADER_LEVEL; };
			class setupSimpleAsset { headerType = WL_HEADER_LEVEL; };
			class slingAddAction { headerType = WL_HEADER_LEVEL; };
			class smokeCurtainAction { headerType = WL_HEADER_LEVEL; };
			class smokeCurtainParticles { headerType = WL_HEADER_LEVEL; };
			class turretVisualizerAction { headerType = WL_HEADER_LEVEL; };
			class vehicleLockAction { headerType = WL_HEADER_LEVEL; };
			class vehicleLockUpdate { headerType = WL_HEADER_LEVEL; };
		};
		class ClientDraw {
			file = "src\core\client\draw";
			class cruiseMissileWarning { headerType = WL_HEADER_LEVEL; };
			class drawAssetName { headerType = WL_HEADER_LEVEL; };
			class drawRadarName { headerType = WL_HEADER_LEVEL; };
			class drawSectorMarker { headerType = WL_HEADER_LEVEL; };
			class ecmJammer { headerType = WL_HEADER_LEVEL; };
			class ewarResult { headerType = WL_HEADER_LEVEL; };
			class getDir { headerType = WL_HEADER_LEVEL; };
			class helmetInterface { headerType = WL_HEADER_LEVEL; };
			class iconColor { headerType = WL_HEADER_LEVEL; };
			class iconDrawMap { headerType = WL_HEADER_LEVEL; };
			class iconDrawMapPrepare { headerType = WL_HEADER_LEVEL; };
			class iconSize { headerType = WL_HEADER_LEVEL; };
			class iconText { headerType = WL_HEADER_LEVEL; };
			class iconType { headerType = WL_HEADER_LEVEL; };
			class initHud { headerType = WL_HEADER_LEVEL; };
			class isScannerMunition { headerType = WL_HEADER_LEVEL; };
			class mapIcons { headerType = WL_HEADER_LEVEL; };
			class scoreboard { headerType = WL_HEADER_LEVEL; };
			class setupUI { headerType = WL_HEADER_LEVEL; };
			class smoothText { headerType = WL_HEADER_LEVEL; };
			class toggleTurretVisualizer { headerType = WL_HEADER_LEVEL; };
			class turretLimits { headerType = WL_HEADER_LEVEL; };
		};
		class ClientInventory {
			file = "src\core\client\inventory";
			class clearButtonClicked { headerType = WL_HEADER_LEVEL; };
			class getLoadouts { headerType = WL_HEADER_LEVEL; };
			class initInventory { headerType = WL_HEADER_LEVEL; };
			class loadoutButtonClicked { headerType = WL_HEADER_LEVEL; };
			class nextButtonClicked { headerType = WL_HEADER_LEVEL; };
			class pageChanged { headerType = WL_HEADER_LEVEL; };
			class previousButtonClicked { headerType = WL_HEADER_LEVEL; };
			class saveButtonClicked { headerType = WL_HEADER_LEVEL; };
			class trimInventoryText { headerType = WL_HEADER_LEVEL; };
		};
		class ClientKill {
			file = "src\core\client\kill";
			class askForgiveness { headerType = WL_HEADER_LEVEL; };
			class deathInfo { headerType = WL_HEADER_LEVEL; };
			class killHistory { headerType = WL_HEADER_LEVEL; };
			class killNotify { headerType = WL_HEADER_LEVEL; };
			class killRewardClient { headerType = WL_HEADER_LEVEL; };
			class punishmentClient { headerType = WL_HEADER_LEVEL; };
			class punishMessage { headerType = WL_HEADER_LEVEL; };
			class refreshKillfeed { headerType = WL_HEADER_LEVEL; };
			class updateKillFeed { headerType = WL_HEADER_LEVEL; };
			class vehicleImmobilized { headerType = WL_HEADER_LEVEL; };
		};
		class ClientMap {
			file = "src\core\client\map";
			class addMapButtonPageLoad { headerType = WL_HEADER_LEVEL; };
			class addMapButtonsDisplay { headerType = WL_HEADER_LEVEL; };
			class addTargetMapButton { headerType = WL_HEADER_LEVEL; };
			class assetButtonAccessControl { headerType = WL_HEADER_LEVEL; };
			class assetButtonFollow { headerType = WL_HEADER_LEVEL; };
			class assetButtonRadarOperate { headerType = WL_HEADER_LEVEL; };
			class assetButtonRadarRotate { headerType = WL_HEADER_LEVEL; };
			class assetMapButtons { headerType = WL_HEADER_LEVEL; };
			class assetMapControl { headerType = WL_HEADER_LEVEL; };
			class captureDisplay { headerType = WL_HEADER_LEVEL; };
			class createInfoMarkers { headerType = WL_HEADER_LEVEL; };
			class designateTeamPriority { headerType = WL_HEADER_LEVEL; };
			class detectUnits { headerType = WL_HEADER_LEVEL; };
			class getSectorFTAsset { headerType = WL_HEADER_LEVEL; };
			class getSideBase { headerType = WL_HEADER_LEVEL; };
			class handleEnemyCapture { headerType = WL_HEADER_LEVEL; };
			class handleSectorIcons { headerType = WL_HEADER_LEVEL; };
			class mapButtonClick { headerType = WL_HEADER_LEVEL; };
			class mapButtonConditions { headerType = WL_HEADER_LEVEL; };
			class mapEachFrame { headerType = WL_HEADER_LEVEL; };
			class replayMap { headerType = WL_HEADER_LEVEL; };
			class replayMapClear { headerType = WL_HEADER_LEVEL; };
			class sectorButtonMark { headerType = WL_HEADER_LEVEL; };
			class sectorButtonMarker { headerType = WL_HEADER_LEVEL; };
			class sectorMapButtons { headerType = WL_HEADER_LEVEL; };
			class sectorMarkerUpdate { headerType = WL_HEADER_LEVEL; };
			class sectorOwnershipHandleClient { headerType = WL_HEADER_LEVEL; };
			class sectorRevealHandle { headerType = WL_HEADER_LEVEL; };
			class sectorScanHandle { headerType = WL_HEADER_LEVEL; };
			class sectorsInitClient { headerType = WL_HEADER_LEVEL; };
			class sectorVoteClient { headerType = WL_HEADER_LEVEL; };
			class selectedTargetsHandle { headerType = WL_HEADER_LEVEL; };
			class targetSelected { headerType = WL_HEADER_LEVEL; };
			class travelTeamPriority { headerType = WL_HEADER_LEVEL; };
			class uavMapButtons { headerType = WL_HEADER_LEVEL; };
		};
		class ClientOrder {
			file = "src\core\client\order";
			class cancelVehicleOrder { headerType = WL_HEADER_LEVEL; };
			class deployment { headerType = WL_HEADER_LEVEL; };
			class executeFastTravel { headerType = WL_HEADER_LEVEL; };
			class executeFastTravelVehicle { headerType = WL_HEADER_LEVEL; };
			class executeParadrop { headerType = WL_HEADER_LEVEL; };
			class findStrongholdBuilding { headerType = WL_HEADER_LEVEL; };
			class orderAircraft { headerType = WL_HEADER_LEVEL; };
			class orderArsenal { headerType = WL_HEADER_LEVEL; };
			class orderCruiseMissile { headerType = WL_HEADER_LEVEL; };
			class orderFundsTransfer { headerType = WL_HEADER_LEVEL; };
			class orderNaval { headerType = WL_HEADER_LEVEL; };
			class orderStronghold { headerType = WL_HEADER_LEVEL; };
			class orderVehicle { headerType = WL_HEADER_LEVEL; };
			class requestPurchase { headerType = WL_HEADER_LEVEL; };
		};
		class ClientPurchase {
			file = "src\core\client\purchase";
			class checkAAPlacement { headerType = WL_HEADER_LEVEL; };
			class checkPlayerCountForAirSpawn { headerType = WL_HEADER_LEVEL; };
			class checkAlliedPlayers { headerType = WL_HEADER_LEVEL; };
			class checkAssetLimit { headerType = WL_HEADER_LEVEL; };
			class checkCarrierLimits { headerType = WL_HEADER_LEVEL; };
			class checkCruiseMissileAvailable { headerType = WL_HEADER_LEVEL; };
			class checkCollaborator { headerType = WL_HEADER_LEVEL; };
			class checkCombatAir { headerType = WL_HEADER_LEVEL; };
			class checkConscription { headerType = WL_HEADER_LEVEL; };
			class checkDead { headerType = WL_HEADER_LEVEL; };
			class checkEwar { headerType = WL_HEADER_LEVEL; };
			class checkFastTravelSL { headerType = WL_HEADER_LEVEL; };
			class checkFastTravelSquad { headerType = WL_HEADER_LEVEL; };
			class checkFunds { headerType = WL_HEADER_LEVEL; };
			class checkGreenSwitch { headerType = WL_HEADER_LEVEL; };
			class checkGroundVehicleDriver { headerType = WL_HEADER_LEVEL; };
			class checkIndependents { headerType = WL_HEADER_LEVEL; };
			class checkInfantryAvailable { headerType = WL_HEADER_LEVEL; };
			class checkInFriendlySector { headerType = WL_HEADER_LEVEL; };
			class checkIsOrdering { headerType = WL_HEADER_LEVEL; };
			class checkNearbyEnemies { headerType = WL_HEADER_LEVEL; };
			class checkNoStronghold { headerType = WL_HEADER_LEVEL; };
			class checkParadropCooldown { headerType = WL_HEADER_LEVEL; };
			class checkPlayerInVehicle { headerType = WL_HEADER_LEVEL; };
			class checkRequirements { headerType = WL_HEADER_LEVEL; };
			class checkResetVehicle { headerType = WL_HEADER_LEVEL; };
			class checkStrongholdFT { headerType = WL_HEADER_LEVEL; };
			class checkSelectedUnits { headerType = WL_HEADER_LEVEL; };
			class checkTargetEnemyBase { headerType = WL_HEADER_LEVEL; };
			class checkTargetReset { headerType = WL_HEADER_LEVEL; };
			class checkTargetSelected { headerType = WL_HEADER_LEVEL; };
			class checkTargetUnlinked { headerType = WL_HEADER_LEVEL; };
			class checkTent { headerType = WL_HEADER_LEVEL; };
			class checkUAVLimit { headerType = WL_HEADER_LEVEL; };
			class purchaseFromMenu { headerType = WL_HEADER_LEVEL; };
			class purchaseMenuAssetAvailability { headerType = WL_HEADER_LEVEL; };
			class purchaseMenuGetUIScale { headerType = WL_HEADER_LEVEL; };
			class purchaseMenuHandleDLC { headerType = WL_HEADER_LEVEL; };
			class purchaseMenuRefresh { headerType = WL_HEADER_LEVEL; };
			class purchaseMenuSetAssetDetails { headerType = WL_HEADER_LEVEL; };
			class purchaseMenuSetItemsList { headerType = WL_HEADER_LEVEL; };
		};
		class Common {
			file = "src\core\common";
			class accessControl { headerType = WL_HEADER_LEVEL; };
			class cleanupCarrier { headerType = WL_HEADER_LEVEL; };
			class dumbMineHandler { headerType = WL_HEADER_LEVEL; };
			class establishStronghold { headerType = WL_HEADER_LEVEL; };
			class findSpawnsInArea { headerType = WL_HEADER_LEVEL; };
			class findSpawnsInMarker { headerType = WL_HEADER_LEVEL; };
			class findSpawnsInSector { headerType = WL_HEADER_LEVEL; };
			class getAirSectorSpawn { headerType = WL_HEADER_LEVEL; };
			class getAngle { headerType = WL_HEADER_LEVEL; };
			class getAssetSide { headerType = WL_HEADER_LEVEL; };
			class getAssetOwnerName { headerType = WL_HEADER_LEVEL; };
			class getAssetTypeName { headerType = WL_HEADER_LEVEL; };
			class getAssetTypeShortName { headerType = WL_HEADER_LEVEL; };
			class getMagazineName { headerType = WL_HEADER_LEVEL; };
			class getMoneySign { headerType = WL_HEADER_LEVEL; };
			class getVehicleWeapons { headerType = WL_HEADER_LEVEL; };
			class grieferCheck { headerType = WL_HEADER_LEVEL; };
			class handleDamage { headerType = WL_HEADER_LEVEL; };
			class handleInstigator { headerType = WL_HEADER_LEVEL; };
			class inAngleCheck { headerType = WL_HEADER_LEVEL; };
			class income { headerType = WL_HEADER_LEVEL; };
			class initAssetData { headerType = WL_HEADER_LEVEL; };
			class initCommon { headerType = WL_HEADER_LEVEL; };
			class initSectors { headerType = WL_HEADER_LEVEL; };
			class isKeyPressed { headerType = WL_HEADER_LEVEL; };
			class lastHitHandler { headerType = WL_HEADER_LEVEL; };
			class missionEndHandle { headerType = WL_HEADER_LEVEL; };
			class newAssetHandle { headerType = WL_HEADER_LEVEL; };
			class parseAssetPurchases { headerType = WL_HEADER_LEVEL; };
			class parsePurchaseList { headerType = WL_HEADER_LEVEL; };
			class prepareStronghold { headerType = WL_HEADER_LEVEL; };
			class protectStronghold { headerType = WL_HEADER_LEVEL; };
			class reloadOverride { headerType = WL_HEADER_LEVEL; };
			class scriptCollector { headerType = WL_HEADER_LEVEL; };
			class slingloadInit { headerType = WL_HEADER_LEVEL; };
			class sortSectorArrays { headerType = WL_HEADER_LEVEL; };
			class uavConnectRefresh { headerType = WL_HEADER_LEVEL; };
			class updateSectorArrays { headerType = WL_HEADER_LEVEL; };
			class varsInit { headerType = WL_HEADER_LEVEL; };
			class warnIncomingMissile { headerType = WL_HEADER_LEVEL; };
		};
		class Server {
			file = "src\core\server";
			class assetRelevanceCheck { headerType = WL_HEADER_LEVEL; };
			class attachDetach { headerType = WL_HEADER_LEVEL; };
			class calcImbalance { headerType = WL_HEADER_LEVEL; };
			class calculateEndResults { headerType = WL_HEADER_LEVEL; };
			class calculateRating { headerType = WL_HEADER_LEVEL; };
			class changeSectorOwnership { headerType = WL_HEADER_LEVEL; };
			class clearPlayerReports { headerType = WL_HEADER_LEVEL; };
			class clearServerStats { headerType = WL_HEADER_LEVEL; };
			class combatAirServer { headerType = WL_HEADER_LEVEL; };
			class createDestroyer { headerType = WL_HEADER_LEVEL; };
			class createUAVCrew { headerType = WL_HEADER_LEVEL; };
			class createVehicleCorrectly { headerType = WL_HEADER_LEVEL; };
			class demolishComplete { headerType = WL_HEADER_LEVEL; };
			class destroyStronghold { headerType = WL_HEADER_LEVEL; };
			class detectNewPlayers { headerType = WL_HEADER_LEVEL; };
			class dumbMineAnnouncer { headerType = WL_HEADER_LEVEL; };
			class ewarGenerate { headerType = WL_HEADER_LEVEL; };
			class factory { headerType = WL_HEADER_LEVEL; };
			class forgiveTeamkill { headerType = WL_HEADER_LEVEL; };
			class forwardBaseUpgrade { headerType = WL_HEADER_LEVEL; };
			class friendlyFireHandleServer { headerType = WL_HEADER_LEVEL; };
			class fundsDatabaseUpdate { headerType = WL_HEADER_LEVEL; };
			class fundsDatabaseWrite { headerType = WL_HEADER_LEVEL; };
			class garbageCollector { headerType = WL_HEADER_LEVEL; };
			class generateEndResultPage { headerType = WL_HEADER_LEVEL; };
			class generateScoreboard { headerType = WL_HEADER_LEVEL; };
			class handleClientRequest { headerType = WL_HEADER_LEVEL; };
			class handleEntityRemoval { headerType = WL_HEADER_LEVEL; };
			class hideObjectOnAll { headerType = WL_HEADER_LEVEL; };
			class incomePayoff { headerType = WL_HEADER_LEVEL; };
			class initServer { headerType = WL_HEADER_LEVEL; };
			class killRewardHandle { headerType = WL_HEADER_LEVEL; };
			class lagMessageHandler { headerType = WL_HEADER_LEVEL; };
			class laserTracker { headerType = WL_HEADER_LEVEL; };
			class manageServer { headerType = WL_HEADER_LEVEL; };
			class missileDestroy { headerType = WL_HEADER_LEVEL; };
			class onDisconnect { headerType = WL_HEADER_LEVEL; };
			class processRunways { headerType = WL_HEADER_LEVEL; };
			class publishRewards { headerType = WL_HEADER_LEVEL; };
			class punishPlayer { headerType = WL_HEADER_LEVEL; };
			class rebalance { headerType = WL_HEADER_LEVEL; };
			class requestScoreboard { headerType = WL_HEADER_LEVEL; };
			class runwayCollector { headerType = WL_HEADER_LEVEL; };
			class selectTarget { headerType = WL_HEADER_LEVEL; };
			class serverEHs { headerType = WL_HEADER_LEVEL; };
			class setScoreboardEntry { headerType = WL_HEADER_LEVEL; };
			class setupNewPlayer { headerType = WL_HEADER_LEVEL; };
			class targetSelectionHandleServer { headerType = WL_HEADER_LEVEL; };
			class uavJammed { headerType = WL_HEADER_LEVEL; };
			class updateVehicleList { headerType = WL_HEADER_LEVEL; };
			class wreckHandler { headerType = WL_HEADER_LEVEL; };
		};
		class ServerSector {
			file = "src\core\server\sector";
			class calcHomeBases { headerType = WL_HEADER_LEVEL; };
			class combatAirServerHandle { headerType = WL_HEADER_LEVEL; };
			class getCapValues { headerType = WL_HEADER_LEVEL; };
			class populateSector { headerType = WL_HEADER_LEVEL; };
			class populateCarrierSector { headerType = WL_HEADER_LEVEL; };
			class sectorCaptureHandle { headerType = WL_HEADER_LEVEL; };
			class sectorRespawner { headerType = WL_HEADER_LEVEL; };
			class sectorsInitServer { headerType = WL_HEADER_LEVEL; };
		};
		class ServerOrder {
			file = "src\core\server\order";
			class orderAir { headerType = WL_HEADER_LEVEL; };
			class orderGround { headerType = WL_HEADER_LEVEL; };
			class orderWater { headerType = WL_HEADER_LEVEL; };
			class processOrder { headerType = WL_HEADER_LEVEL; };
		};
	};
	class WLC {
		class Default {
			file = "src\scripts\WLC";
			class action { headerType = WL_HEADER_LEVEL; };
			class getLevelInfo { headerType = WL_HEADER_LEVEL; };
			class levelUp { headerType = WL_HEADER_LEVEL; };
			class onRespawn { headerType = WL_HEADER_LEVEL; };
			class setScore { headerType = WL_HEADER_LEVEL; };
		};
	};
	class WLM {
		class WLM {
			file = "src\scripts\WLM";
			class applyCustomization { headerType = WL_HEADER_LEVEL; };
			class applyLoadoutAircraft { headerType = WL_HEADER_LEVEL; };
			class applyLoadoutVehicle { headerType = WL_HEADER_LEVEL; };
			class applyTexture { headerType = WL_HEADER_LEVEL; };
			class applyPylon { headerType = WL_HEADER_LEVEL; };
			class applyVehicle { headerType = WL_HEADER_LEVEL; };
			class calculateFreeRearmEligibility { headerType = WL_HEADER_LEVEL; };
			class changeHorn { headerType = WL_HEADER_LEVEL; };
			class checkTurretLocality { headerType = WL_HEADER_LEVEL; };
			class constructAircraftPylons { headerType = WL_HEADER_LEVEL; };
			class constructPresetMenu { headerType = WL_HEADER_LEVEL; };
			class constructVehicleMagazine { headerType = WL_HEADER_LEVEL; };
			class getMagazineTooltip { headerType = WL_HEADER_LEVEL; };
			class initMenu { headerType = WL_HEADER_LEVEL; };
			class menuTextOverrides { headerType = WL_HEADER_LEVEL; };
			class moveSmokes { headerType = WL_HEADER_LEVEL; };
			class rearmAircraft { headerType = WL_HEADER_LEVEL; };
			class rearmVehicle { headerType = WL_HEADER_LEVEL; };
			class saveLoadout { headerType = WL_HEADER_LEVEL; };
			class selectLoadout { headerType = WL_HEADER_LEVEL; };
			class startRearmVehicle { headerType = WL_HEADER_LEVEL; };
			class switchUser { headerType = WL_HEADER_LEVEL; };
			class textureLists { headerType = WL_HEADER_LEVEL; };
			class textureSlots { headerType = WL_HEADER_LEVEL; };
			class wipePylonSaves { headerType = WL_HEADER_LEVEL; };
		};
	};
};
