// MP Security
class CfgRemoteExec {
	class Functions {
		mode = 1;
		jip = 1;

		class APS_fnc_deviceJammer {allowedTargets = 0;};
		class APS_fnc_friendlyWarning {allowedTargets = 0;};
		class APS_fnc_lagProtectionServer {allowedTargets = 2;};
		class APS_fnc_projectileStateUpdate {allowedTargets = 0;};
		class APS_fnc_report {allowedTargets = 0;};
		class APS_fnc_serverHandleAPS {allowedTargets = 2;};
		class APS_fnc_setupProjectiles {allowedTargets = 0;};
		class DIS_fnc_remoteMunition {allowedTargets = 0;};
		class DIS_fnc_setupExtendedSam {allowedTargets = 0;};
		class DIS_fnc_startMissileCamera {allowedTargets = 0;};
		class KST_fnc_explode {allowedTargets = 0;};
		class KST_fnc_rocket {allowedTargets = 0;};
		class KST_fnc_setParent {allowedTargets = 0;};
		class MENU_fnc_execCode {allowedTargets = 2;};
		class MENU_fnc_reportPlayer {allowedTargets = 2;};
		class POLL_fnc_selectOption {allowedTargets = 0;};
		class SQD_fnc_server {allowedTargets = 2;};
		class WL2_fnc_addMissileToMag {allowedTargets = 0;};
		class WL2_fnc_airRearmAction {allowedTargets = 0;};
		class WL2_fnc_attachDetach {allowedTargets = 0;};
		class WL2_fnc_catapultAction {allowedTargets = 0;};
		class WL2_fnc_claimAction {allowedTargets = 1;};
		class WL2_fnc_clearPlayerReports {allowedTargets = 0;};
		class WL2_fnc_clearServerStats {allowedTargets = 2;};
		class WL2_fnc_controlGunnerAction {allowedTargets = 0;};
		class WL2_fnc_cruiseMissileWarning {allowedTargets = 0;};
		class WL2_fnc_demolishAction {allowedTargets = 0;};
		class WL2_fnc_demolishComplete {allowedTargets = 0;};
		class WL2_fnc_deployableAddAction {allowedTargets = 1;};
		class WL2_fnc_deployCrateAction {allowedTargets = 1;};
		class WL2_fnc_destroyStronghold {allowedTargets = 0;};
		class WL2_fnc_earthquake {allowedTargets = 0;};
		class WL2_fnc_forgiveTeamkill {allowedTargets = 2;};
		class WL2_fnc_handleClientRequest {allowedTargets = 2;};
		class WL2_fnc_handleEntityRemoval {allowedTargets = 2;};
		class WL2_fnc_hideObjectOnAll {allowedTargets = 0;};
		class WL2_fnc_jammerAction {allowedTargets = 0;};
		class WL2_fnc_killNotify {allowedTargets = 0;};
		class WL2_fnc_killRewardHandle {allowedTargets = 2;};
		class WL2_fnc_lagMessageHandler {allowedTargets = 2;};
		class WL2_fnc_missileDestroy {allowedTargets = 2;};
		class WL2_fnc_mutePlayer {allowedTargets = 0;};
		class WL2_fnc_punishPlayer {allowedTargets = 2;};
		class WL2_fnc_pingFix {allowedTargets = 1;};
		class WL2_fnc_prepareStronghold {allowedTargets = 0;};
		class WL2_fnc_protectStronghold {allowedTargets = 0;};
		class WL2_fnc_radarOperateAction {allowedTargets = 1;};
		class WL2_fnc_radarRotateAction {allowedTargets = 1;};
		class WL2_fnc_rearmAction {allowedTargets = 1;};
		class WL2_fnc_rebalance {allowedTargets = 2;};
		class WL2_fnc_reconOpticsAction {allowedTargets = 0;};
		class WL2_fnc_refuelAction {allowedTargets = 0;};
		class WL2_fnc_reloadOverride {allowedTargets = 0;};
		class WL2_fnc_removeAction {allowedTargets = 1;};
		class WL2_fnc_repairAction {allowedTargets = 1;};
		class WL2_fnc_reportTargets {allowedTargets = 0;};
		class WL2_fnc_requestScoreboard {allowedTargets = 2;};
		class WL2_fnc_restockAction {allowedTargets = 0;};
		class WL2_fnc_revive {allowedTargets = 0;};
		class WL2_fnc_sectorRevealHandle {allowedTargets = 0;};
		class WL2_fnc_scannerAction {allowedTargets = 0;};
		class WL2_fnc_setupForwardBaseAction {allowedTargets = 0;};
		class WL2_fnc_setupForwardBaseMp {allowedTargets = 0;};
		class WL2_fnc_slingAddAction {allowedTargets = 1;};
		class WL2_fnc_slingloadInit {allowedTargets = 0;};
		class WL2_fnc_smokeCurtainAction {allowedTargets = 0;};
		class WL2_fnc_smokeCurtainParticles {allowedTargets = 0;};
		class WL2_fnc_punishMessage {allowedTargets = 0;};
		class WL2_fnc_turretVisualizerAction {allowedTargets = 0;};
		class WL2_fnc_uavConnectRefresh {allowedTargets = 0;};
		class WL2_fnc_uavJammed {allowedTargets = 2;};
		class WL2_fnc_updateVehicleList {allowedTargets = 2;};
		class WL2_fnc_vehicleImmobilized {allowedTargets = 0;};
		class WL2_fnc_vehicleLockAction {allowedTargets = 1;};
		class WL2_fnc_vehicleLockUpdate {allowedTargets = 0;};
		class WL2_fnc_warnIncomingMissile {allowedTargets = 0;};
		class WLM_fnc_applyPylon {allowedTargets = 0;};
		class WLM_fnc_applyVehicle {allowedTargets = 0;};
		class WLM_fnc_changeHorn {allowedTargets = 0;};
		class WLM_fnc_moveSmokes {allowedTargets = 0;};
		class WLM_fnc_rearmVehicle {allowedTargets = 0;};

		//Don't touch
		class BIS_fnc_effectKilled {allowedTargets = 0; jip = 0;};
		class BIS_fnc_effectKilledAirDestruction {allowedTargets = 0; jip = 0;};
		class BIS_fnc_effectKilledSecondaries {allowedTargets = 0; jip = 0;};
		class BIS_fnc_objectVar {allowedTargets = 0; jip = 0;};
		class BIS_fnc_setCustomSoundController {allowedTargets = 0; jip = 0;};
		class BIS_fnc_debugConsoleExec {allowedTargets = 0; jip = 0;};
		class BIS_fnc_setIdentity {allowedTargets = 0; jip = 0;};
		class BIS_fnc_curatorRespawn {allowedTargets = 0; jip = 0;};
		class BIS_fnc_fire {allowedTargets = 0; jip = 0;};
	};

	class Commands {
		mode = 1;

		class diag_log {allowedTargets = 2;};
		class lock {allowedTargets = 0;};
		class lockCameraTo {allowedTargets = 0;};
		class lookAt {allowedTargets = 0;};
		class moveInDriver {allowedTargets = 0;};
		class playSoundUI {allowedTargets = 0;};
		class removeWeaponGlobal {allowedTargets = 0;};
		class selectLeader {allowedTargets = 0;};
		class setAmmoCargo {allowedTargets = 0;};
		class setAutonomous {allowedTargets = 0;};
		class setDate {allowedTargets = 0;};
		class setFuel {allowedTargets = 0;};
		class setFuelCargo {allowedTargets = 0;};
		class setFuelConsumptionCoef {allowedTargets = 0;};
		class setMass {allowedTargets = 0;};
		class setPylonLoadOut {allowedTargets = 0;};
		class setAmmoOnPylon {allowedTargets = 0;};
		class setPhysicsCollisionFlag {allowedTargets = 0;};
		class setPylonsPriority {allowedTargets = 0;};
		class setRepairCargo {allowedTargets = 0;};
		class setShotParents {allowedTargets = 0;};
		class setVehicleAmmoDef {allowedTargets = 0;};
		class setVehicleRadar {allowedTargets = 0;};
		class setVehicleReceiveRemoteTargets {allowedTargets = 0;};
		class setVehicleReportOwnPosition {allowedTargets = 0;};
		class setVehicleReportRemoteTargets {allowedTargets = 0;};
		class setVehicleTIPars {allowedTargets = 0;};
		class setVelocityModelSpace {allowedTargets = 2;};
		class switchMove {allowedTargets = 0;};
		class systemChat {allowedTargets = 0;};
	};
};